name: docs
on:
  push:
    branches:
    - master

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Install sphinx
      run: sudo apt-get install python3-sphinx
    - name: Build docs
      run: |
        cd docs
        make html
